
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Date;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author korjk
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 600, 200));

        jLabel1.setText("Помилка при введенні дати народження. ");

        jLabel2.setText("Ви ввели дані не в форматі рік/місяць/день або якесь з чисел більше/менше за можливе");

        jButton2.setText("OK");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Вивести знак зодіаку і інформацію");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Рік");

        jLabel4.setText("День");

        jLabel5.setText("Місяць");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(69, 69, 69)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGap(37, 37, 37))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var Year = jTextField1.getText();
        var Month = jTextField2.getText();
        var Day = jTextField3.getText();

        try {
            int year = parseInt(Year);
            int day = parseInt(Day);
            int month = parseInt(Month);
            if ((year <= 0) || (month <= 0 || month >= 13) || (day <= 0 || day >= 32) || (month == 2 && day > 29) || (month == 2 && day == 29 && year % 4 != 0) || (day > 30 && (month == 4 || month == 6 || month == 9 || month == 11)) || (day > 31)) {
                JOptionPane.showMessageDialog(null, "Помилка: Дата введена неправильно або не може існувати.", "Помилка", JOptionPane.ERROR_MESSAGE);
            } else {
                String[] zodiacinfo = getZodiacSign(month, day);
                JOptionPane.showMessageDialog(null, zodiacinfo[0] + "\n" + zodiacinfo[1], "Знак зодіаку", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Помилка: Дата введена неправильно або не може існувати.", "Помилка", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    private String[] getZodiacSign(int month, int day) {
        String[] zodiacSigns = {
            "Козоріг", "Водолій", "Риби", "Овен",
            "Телець", "Близнюки", "Рак", "Лев",
            "Діва", "Терези", "Скорпіон", "Стрілець"
        };
        String[] ZodiacInfo = new String[2];
        if (month > 11) {
            if (day >= 23) {
                ZodiacInfo[0] = zodiacSigns[0];
                ZodiacInfo[1] = "Головна якість Козорогів — стриманість: про них зазвичай говорять, що вони \"застебнуті на всі гудзики\". Це не означає, що у представників знака немає емоцій, просто вони ховають їх глибоко всередині, де вони вирують з величезною силою, яку не видно оточенню — вони вважають Козорогів сухарями";
            } else {
                ZodiacInfo[0] = zodiacSigns[11];
                ZodiacInfo[1] = "Стрілець — один із найактивніших і найенергійніших знаків зодіаку, яким під силу все, крім одного: вони категорично не можуть сидіти на місці. Їх тягнуть нові відчуття і враження, тому серед представників знака дуже багато мандрівників.";
            }
        } else if (month == 1) {
            if (day > 20) {
                ZodiacInfo[0] = zodiacSigns[1];
                ZodiacInfo[1] = "Водолії — не найпростіший, через свою неоднозначність і суперечливість, знак зодіаку. Його представники вважають своє життя прісним, тому постійно перебувають в пошуку нових вражень і відчуттів. Не дивно, що, відшукавши їх, вони часто потрапляють в безглузді, а часом і вельми неприємні ситуації";
            } else {
                ZodiacInfo[0] = zodiacSigns[0];
                ZodiacInfo[1] = "Головна якість Козорогів — стриманість: про них зазвичай говорять, що вони \"застебнуті на всі гудзики\". Це не означає, що у представників знака немає емоцій, просто вони ховають їх глибоко всередині, де вони вирують з величезною силою, яку не видно оточенню — вони вважають Козорогів сухарями";
            }
        } else if (month == 2) {
            if (day > 20) {
                ZodiacInfo[0] = zodiacSigns[2];
                ZodiacInfo[1] = "Риби — також дуже чутливий знак: вони вміють зчитувати інформацію буквально з повітря, тому про них говорять, як про людей з потужною інтуїцією. Представники знака настільки добре відчувають інших людей, що часом здається, що вони бачать оточення наскрізь і вміють читати думки.";
            } else {
                ZodiacInfo[0] = zodiacSigns[1];
                ZodiacInfo[1] = "Водолії — не найпростіший, через свою неоднозначність і суперечливість, знак зодіаку. Його представники вважають своє життя прісним, тому постійно перебувають в пошуку нових вражень і відчуттів. Не дивно, що, відшукавши їх, вони часто потрапляють в безглузді, а часом і вельми неприємні ситуації";
            }
        } else if (month == 3) {
            if (day > 20) {
                ZodiacInfo[0] = zodiacSigns[3];
                ZodiacInfo[1] = "За натурою вони – справжні лідери, бунтарі і одночасно ідеалісти, які вірять у світле майбутнє і вічне кохання. Вони вміють ставити перед собою мету і знають, як її досягти: найчастіше, вони беруть своє напиранням, але за необхідності можуть піти і обхідними шляхами.";
            } else {
                ZodiacInfo[0] = zodiacSigns[2];
                ZodiacInfo[1] = "Риби — також дуже чутливий знак: вони вміють зчитувати інформацію буквально з повітря, тому про них говорять, як про людей з потужною інтуїцією. Представники знака настільки добре відчувають інших людей, що часом здається, що вони бачать оточення наскрізь і вміють читати думки.";
            }
        } else if (month == 4) {
            if (day > 20) {
                ZodiacInfo[0] = zodiacSigns[4];
                ZodiacInfo[1] = "Найбільше представники цього знака люблять і цінують земні задоволення: смачну їжу, хороше вино, гарний одяг, побутові зручності і комфорт. Тельці консервативні – вони негативно ставляться до змін, не прагнуть до них самі і не вітають вчинки інших, коли ті затівають якісь пертурбації – як в особистому, так і суспільному житті.";
            } else {
                ZodiacInfo[0] = zodiacSigns[3];
                ZodiacInfo[1] = "За натурою вони – справжні лідери, бунтарі і одночасно ідеалісти, які вірять у світле майбутнє і вічне кохання. Вони вміють ставити перед собою мету і знають, як її досягти: найчастіше, вони беруть своє напиранням, але за необхідності можуть піти і обхідними шляхами.";
            }
        } else if (month == 5) {
            if (day > 21) {
                ZodiacInfo[0] = zodiacSigns[5];
                ZodiacInfo[1] = "Близнята – дуже яскравий знак, під яким народжуються неабиякі інтелектуальні особистості: письменники, поети, журналісти, юристи, громадські діячі. Їм властивий всебічний погляд на будь-який предмет, вони просто не вміють дивитися на світ однобоко – їм обов'язково потрібно врахувати безліч різних чинників, щоб володіти повнотою картини.";
            } else {
                ZodiacInfo[0] = zodiacSigns[4];
                ZodiacInfo[1] = "Найбільше представники цього знака люблять і цінують земні задоволення: смачну їжу, хороше вино, гарний одяг, побутові зручності і комфорт. Тельці консервативні – вони негативно ставляться до змін, не прагнуть до них самі і не вітають вчинки інших, коли ті затівають якісь пертурбації – як в особистому, так і суспільному житті.";
            }
        } else if (month == 6) {
            if (day > 21) {
                ZodiacInfo[0] = zodiacSigns[6];
                ZodiacInfo[1] = "Його представники справляють враження людей холодних, стриманих і відсторонених, їх ніби огортає ореол таємничості, але за цією \"бронею\" часто ховається тонка душевна організація, чутливість і вразливість. Вони дуже важко і глибоко переживають будь-які душевні потрясіння – особливо любовні драми, зради і втрати.";
            } else {
                ZodiacInfo[0] = zodiacSigns[5];
                ZodiacInfo[1] = "Близнята – дуже яскравий знак, під яким народжуються неабиякі інтелектуальні особистості: письменники, поети, журналісти, юристи, громадські діячі. Їм властивий всебічний погляд на будь-який предмет, вони просто не вміють дивитися на світ однобоко – їм обов'язково потрібно врахувати безліч різних чинників, щоб володіти повнотою картини.";
            }
        } else if (month == 7) {
            if (day > 22) {
                ZodiacInfo[0] = zodiacSigns[7];
                ZodiacInfo[1] = "Леви – товариські, добрі і щедрі: дізнавшись, що хтось потребує допомоги, вони з радістю її нададуть, але водночас пишатимуться собою і обов'язково скористаються можливістю похизуватися власним благородством і піднести свій вчинок з вигідного боку. Але Леви, і це позитивна їх якість, не люблять і не вміють брехати, а зачинати інтриги, пліткувати і лихословити – взагалі не їхній стиль поведінки.";
            } else {
                ZodiacInfo[0] = zodiacSigns[6];
                ZodiacInfo[1] = "Його представники справляють враження людей холодних, стриманих і відсторонених, їх ніби огортає ореол таємничості, але за цією \"бронею\" часто ховається тонка душевна організація, чутливість і вразливість. Вони дуже важко і глибоко переживають будь-які душевні потрясіння – особливо любовні драми, зради і втрати.";
            }
        } else if (month == 8) {
            if (day > 23) {
                ZodiacInfo[0] = zodiacSigns[8];
                ZodiacInfo[1] = "Дів, на відміну від інших знаків, не дратує рутинна і монотонна робота, вони, подібно до працьовитої Попелюшки, годинами можуть перебирати квасолю, відокремлюючи червону від білої. Представники знака мають аналітичний розум: ухвалюючи важливе рішення, вони легко прораховують всі \"за\" і \"проти\" і вкрай рідко помиляються.";
            } else {
                ZodiacInfo[0] = zodiacSigns[7];
                ZodiacInfo[1] = "Леви – товариські, добрі і щедрі: дізнавшись, що хтось потребує допомоги, вони з радістю її нададуть, але водночас пишатимуться собою і обов'язково скористаються можливістю похизуватися власним благородством і піднести свій вчинок з вигідного боку. Але Леви, і це позитивна їх якість, не люблять і не вміють брехати, а зачинати інтриги, пліткувати і лихословити – взагалі не їхній стиль поведінки.";
            }
        } else if (month == 9) {
            if (day > 23) {
                ZodiacInfo[0] = zodiacSigns[9];
                ZodiacInfo[1] = "Люди, що народилися під ним, як і їхнє позначення — Терези з двома чашами, завжди і у всьому прагнуть до гармонії і рівноваги. Правда, для цього їм доводиться довго вагатися — сумніви переважують то в один, то в інший бік, але результат, який дає представникам знака спокій і стабільність, того вартий. Іноді ця якість з позитивниї перетворюється на негативну — схильність до коливань і метань робить їх ненадійними партнерами як у діловому, так і в особистому житті. ";
            } else {
                ZodiacInfo[0] = zodiacSigns[8];
                ZodiacInfo[1] = "Дів, на відміну від інших знаків, не дратує рутинна і монотонна робота, вони, подібно до працьовитої Попелюшки, годинами можуть перебирати квасолю, відокремлюючи червону від білої. Представники знака мають аналітичний розум: ухвалюючи важливе рішення, вони легко прораховують всі \"за\" і \"проти\" і вкрай рідко помиляються.";
            }
        } else if (month == 10) {
            if (day > 22) {
                ZodiacInfo[0] = zodiacSigns[10];
                ZodiacInfo[1] = "Скорпіони мають потужну харизму, що робить їх прекрасними лідерами і керівниками: вони можуть взяти в роботу будь-яку — найскладнішу і важкореалізовану — ідею, і не тільки зацікавитися нею самі, але і захопити інших — співробітників і колег. Правда, самі вони після цього можуть швидко охолонути до справи, якою займаються, і переключитися на інше — мінливість теж у них в крові.";
            } else {
                ZodiacInfo[0] = zodiacSigns[9];
                ZodiacInfo[1] = "Люди, що народилися під ним, як і їхнє позначення — Терези з двома чашами, завжди і у всьому прагнуть до гармонії і рівноваги. Правда, для цього їм доводиться довго вагатися — сумніви переважують то в один, то в інший бік, але результат, який дає представникам знака спокій і стабільність, того вартий. Іноді ця якість з позитивниї перетворюється на негативну — схильність до коливань і метань робить їх ненадійними партнерами як у діловому, так і в особистому житті.";
            }
        } else if (month == 11) {
            if (day > 22) {
                ZodiacInfo[0] = zodiacSigns[11];
                ZodiacInfo[1] = "Стрілець — один із найактивніших і найенергійніших знаків зодіаку, яким під силу все, крім одного: вони категорично не можуть сидіти на місці. Їх тягнуть нові відчуття і враження, тому серед представників знака дуже багато мандрівників.";
            } else {
                ZodiacInfo[0] = zodiacSigns[10];
                ZodiacInfo[1] = "Скорпіони мають потужну харизму, що робить їх прекрасними лідерами і керівниками: вони можуть взяти в роботу будь-яку — найскладнішу і важкореалізовану — ідею, і не тільки зацікавитися нею самі, але і захопити інших — співробітників і колег. Правда, самі вони після цього можуть швидко охолонути до справи, якою займаються, і переключитися на інше — мінливість теж у них в крові.";
            }
        } else if (month == 12) {
            if (day > 22) {
                ZodiacInfo[0] = zodiacSigns[0];
                ZodiacInfo[1] = "Головна якість Козорогів — стриманість: про них зазвичай говорять, що вони \"застебнуті на всі гудзики\". Це не означає, що у представників знака немає емоцій, просто вони ховають їх глибоко всередині, де вони вирують з величезною силою, яку не видно оточенню — вони вважають Козорогів сухарями";
            } else {
                ZodiacInfo[0] = zodiacSigns[11];
                ZodiacInfo[1] = "Стрілець — один із найактивніших і найенергійніших знаків зодіаку, яким під силу все, крім одного: вони категорично не можуть сидіти на місці. Їх тягнуть нові відчуття і враження, тому серед представників знака дуже багато мандрівників.";
            }
        }
        return ZodiacInfo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
